backend:
  name: git
  repo: your-github-username/my-blog
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "excerpt", label: "Excerpt", widget: "text" }
      - { name: "body", label: "Body", widget: "markdown" }
